services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  # Ceph Monitor
  ceph-mon:
    image: quay.io/ceph/ceph:v18.2.7
    restart: always
    hostname: ceph-mon
    volumes:
      - ./ceph/etc:/etc/ceph
      - ./ceph/lib:/var/lib/ceph
      - ./ceph/logs:/var/log/ceph
    environment:
      - MON_IP=127.0.0.1
      - CEPH_PUBLIC_NETWORK=0.0.0.0/0
      - CLUSTER=ceph
    command: >
      bash -c "
        mkdir -p /var/lib/ceph/mon/ceph-ceph-mon &&
        ceph-authtool --create-keyring /tmp/ceph.mon.keyring --gen-key -n mon. &&
        ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *' &&
        ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring &&
        monmaptool --create --add ceph-mon 127.0.0.1 --fsid $(uuidgen) /tmp/monmap &&
        echo '[global]
        fsid = $(uuidgen)
        mon_host = 127.0.0.1
        mon initial members = ceph-mon
        osd pool default size = 1
        osd pool default min size = 1
        osd crush chooseleaf type = 0
        osd journal size = 100
        public network = 0.0.0.0/0
        cluster network = 0.0.0.0/0
        ' > /etc/ceph/ceph.conf &&
        ceph-mon --mkfs -i ceph-mon --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring &&
        ceph-mon -i ceph-mon --public-addr 127.0.0.1:6789
      "

  # Ceph Manager
  ceph-mgr:
    image: quay.io/ceph/ceph:v18.2.7
    restart: always
    hostname: ceph-mgr
    volumes:
      - ./ceph/etc:/etc/ceph
      - ./ceph/lib:/var/lib/ceph
      - ./ceph/logs:/var/log/ceph
    environment:
      - CLUSTER=ceph
    depends_on:
      - ceph-mon
    ports:
      - "8443:8443"
      - "8003:8003"
    command: >
      bash -c "
        sleep 10 &&
        mkdir -p /var/lib/ceph/mgr/ceph-ceph-mgr &&
        ceph auth get-or-create mgr.ceph-mgr mon 'allow profile mgr' osd 'allow *' mds 'allow *' -o /var/lib/ceph/mgr/ceph-ceph-mgr/keyring &&
        ceph-mgr -i ceph-mgr
      "

  # Ceph Object Storage Daemon (OSD)
  ceph-osd:
    image: quay.io/ceph/ceph:v18.2.7
    restart: always
    hostname: ceph-osd
    privileged: true
    volumes:
      - ./ceph/etc:/etc/ceph
      - ./ceph/lib:/var/lib/ceph
      - ./ceph/osd:/var/lib/ceph/osd
      - ./ceph/logs:/var/log/ceph
    environment:
      - CLUSTER=ceph
    depends_on:
      - ceph-mon
    command: >
      bash -c "
        sleep 15 &&
        mkdir -p /var/lib/ceph/osd/ceph-0 &&
        ceph osd create --id 0 &&
        ceph-authtool --create-keyring /var/lib/ceph/osd/ceph-0/keyring --name osd.0 --add-key $(ceph auth get-or-create osd.0 mon 'allow profile osd' osd 'allow *' -o /dev/stdout) &&
        ceph-osd -i 0 --mkfs --mkkey &&
        ceph auth add osd.0 osd 'allow *' mon 'allow profile osd' -i /var/lib/ceph/osd/ceph-0/keyring &&
        ceph-osd -i 0 -f
      "

  # Ceph RadosGW (Object Storage)
  ceph-rgw:
    image: quay.io/ceph/ceph:v18.2.7
    restart: always
    hostname: ceph-rgw
    volumes:
      - ./ceph/etc:/etc/ceph
      - ./ceph/lib:/var/lib/ceph
      - ./ceph/logs:/var/log/ceph
    environment:
      - CLUSTER=ceph
    depends_on:
      - ceph-mon
      - ceph-osd
    ports:
      - "7480:7480"
    command: >
      bash -c "
        sleep 20 &&
        mkdir -p /var/lib/ceph/radosgw/ceph-rgw &&
        ceph auth get-or-create client.rgw ceph-rgw osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/ceph-rgw/keyring &&
        radosgw -n client.rgw.ceph-rgw -k /var/lib/ceph/radosgw/ceph-rgw/keyring -f
      "