services:
  silo:
    image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=siloadmin
      - MINIO_ROOT_PASSWORD=siloadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"